config_home := "$HOME/.claude/"
pwd := absolute_path(".")

# Display this help
default:
  @just --list --unsorted

# Configure all tools
setup: create-symlinks

# Create symlinks to the config files
create-symlinks:
    mkdir -p {{config_home}}
    ln -sf {{pwd}}/skills {{config_home}}/


