source ~/.zplug/init.zsh

zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
zplug "themes/gnzh", from:oh-my-zsh, as:theme
zplug "plugins/git", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "jeffreytse/zsh-vi-mode"

if ! zplug check; then
  zplug install
fi

zplug load

HIST_STAMPS="mm/dd/yyyy"

setopt noautomenu
setopt nomenucomplete

# Functions
alias docker-stop-all='docker stop $(docker ps -aq) && docker rm $(docker ps -aq)'

function f {
  # Prompt for directory using fd + fzf
  local selection
  selection=$(fd --type directory --base-directory "$HOME" \
                 | fzf --height=50% --padding=1% --border=double \
                       --header="CTRL-C or ESC to quit") || return

  # If user aborted fzf (Exit status != 0), bail out cleanly
  # (The '|| return' handles it.)

  # Compose the full path
  local target="$HOME/$selection"

  # Check if the directory still exists
  if [[ -d $target ]]; then
    cd -- "$target" || echo "Failed to cd into '$target'"
  else
    echo "Directory '$target' does not exist."
  fi
}

# Variables
export PATH="$HOME/.local/bin:$HOME/scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR="nvim"
export TERM="xterm-256color"

alias l="ls -lh"
alias la="ls -lha"
alias lt="ls -ltr"
alias lat="ls -latr"

alias v="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"

eval "$(direnv hook zsh)"
eval "$(just --completions zsh)"
eval "$(starship init zsh)"

# go
export GOPATH="$HOME/go"
export PATH="$HOME/go/bin:/usr/local/go/bin:$PATH"
