[GLOBAL]
pants_version = "2.32.0"
plugins = ["pants-plugins @ git+ssh://git@github.com/Ivanipani/pants-plugins.git@faae879"]

backend_packages = [
    "pants.backend.docker",
    "pants_plugins",
]

[docker]
use_buildx = true

[docker.registries.poochella]
address = "us-east4-docker.pkg.dev/adept-fountain-498903-t7/poochella"
default = true
