[global]
keyboard = "en-us"
country = "us"
fqdn = "control01.local"
mailto = "root@localhost"
timezone = "America/New_York"
root_password = "babybaby"
root-ssh-keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICTl/C06oyAMQiGgvUyH4eT2C0sPsIEqnT2nDNHDQ5j9 ivanperdomo@Ivans-MacBook-Pro.local"
]
reboot-on-error = false

[network]
source = "from-dhcp"

[network.interface-name-pinning]
enabled = true

[disk-setup]
filesystem = "zfs"
disk-list = ["sda"]
zfs = { raid = "raid0" }
