---
- name: Install development tools
  ansible.builtin.package:
    name:
      - acl
      - zsh
      - neovim
      - direnv
      - fd-find
      - fzf
      - git
      - wget
    state: present

- name: Download starship installer
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: '0755'

- name: Install starship
  ansible.builtin.shell:
    cmd: /tmp/starship-install.sh --yes
    creates: /usr/local/bin/starship

- name: Download just installer
  ansible.builtin.get_url:
    url: https://just.systems/install.sh
    dest: /tmp/just-install.sh
    mode: '0755'

- name: Install just
  ansible.builtin.shell:
    cmd: /tmp/just-install.sh --to /usr/local/bin
    creates: /usr/local/bin/just

- name: Download zellij
  ansible.builtin.get_url:
    url: https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/zellij.tar.gz

- name: Install zellij
  ansible.builtin.shell:
    cmd: tar -xzf /tmp/zellij.tar.gz -C /usr/local/bin zellij && chmod +x /usr/local/bin/zellij
    creates: /usr/local/bin/zellij

- name: Download neovim
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.11.6/nvim-linux-x86_64.tar.gz
    dest: /tmp/nvim.tar.gz

- name: Install neovim
  ansible.builtin.shell:
    cmd: tar -xzf /tmp/nvim.tar.gz -C /usr/local/bin && chmod +x /usr/local/bin/zellij
    creates: /usr/local/bin/nvim

# - name: Download Go
#   ansible.builtin.get_url:
#     url: https://go.dev/dl/go1.26.1.linux-amd64.tar.gz
#     dest: /tmp/go.tar.gz
# #
# - name: Install Go
#   ansible.builtin.shell:
#     cmd: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go.tar.gz
#     creates: /usr/local/go/bin/go

- name: Create pani user
  ansible.builtin.user:
    name: pani
    state: present
    groups:
      - promoter
      - talent
      - sudo
    shell: /bin/zsh
    home: /home/pani

- name: Set up SSH authorized key for pani
  ansible.posix.authorized_key:
    user: pani
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
    state: present

- name: Install zplug
  ansible.builtin.git:
    repo: https://github.com/zplug/zplug.git
    dest: /home/pani/.zplug
    version: main
  become: true
  become_user: pani


- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:Ivanipani/dotfiles.git
    dest: /home/pani/dotfiles
    version: main
  become: false
  become_user: pani

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: /home/pani/.config
    state: directory
    owner: pani
    group: pani
    mode: "0755"

- name: Run zsh setup script
  ansible.builtin.command:
    cmd: zsh ./setup.sh
    chdir: /home/pani/dotfiles/zsh
  become: true
  become_user: pani
