- name: Ensure /opt/uv directory exists
  ansible.builtin.file:
    path: /opt/uv
    state: directory
    mode: "0755"

- name: Download uv release
  ansible.builtin.get_url:
    url: https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/uv.tar.gz

- name: Install uv
  ansible.builtin.unarchive:
    src: /tmp/uv.tar.gz
    dest: /opt/uv
    remote_src: true
    extra_opts: ['--strip-components=1']
    creates: /opt/uv/uv

- name: Symlink uv binary
  ansible.builtin.file:
    src: /opt/uv/uv
    dest: /opt/bin/uv
    state: link

- name: Symlink uvx binary
  ansible.builtin.file:
    src: /opt/uv/uvx
    dest: /opt/bin/uvx
    state: link


# - name: Install Pantsbuild
#   ansible.builtin.get_url:
#     url: https://static.pantsbuild.org/setup/get-pants.sh
#     dest: /tmp/pants-install.sh
#     mode: "0755"
# - name: Run pants installer script
#   ansible.builtin.shell:
#     cmd: /tmp/pants-install.sh --bin-dir /usr/bin
#     creates: /usr/bin/pants
