apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcs-s3
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lUtoUxEn4Zdw/iJcIHD58n43Z4ZgdoN8+vkbeQEUq9iopNuEYn2yh3CoGf/ksGsLCp0YqNGfrQOgXgvXEg==,iv:g0WiaNjf++0yQpTIPNA8fTZGrg7hImEotn2kWLOEJjY=,tag:1f/MeVmvzoUsKwILZjIwOw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:U8v57kZZw6NHILfLEOYi/TD5MPhcvVcWY4k58Pq6Po+lqA+S4cnoLA==,iv:jPDS1D9Cm2TitIQdIV30+wHcMhkWGPhae9W1xSKhJwo=,tag:Zn32bF1niw2qezoHH7fw5Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:hdbwHYA7PtxZ8x13D/GVnJlQHK7YPd7OnxYW+TOY,iv:2N94xS7c5U1u+KxbWgTE6cG5LDOy0yYDM4bX8qQb10w=,tag:chCjKvf+8lgFFDbERRZ0Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZjRlcTVRVkRjVm9UYXJq
            bE15NzdlNjRrTXMyZFBoM2hrRUo2UEw0dXo0CjBMMitQVWhLVFBvdGRlWTFjYm80
            ZGJRZmJjalZkcC9sY3dYQlZiMmtSUHcKLS0tIDhwTnpNMEk0RCtSMDZ3STd5Rlhk
            RXFGaXUzQnY2dzRDcmlHVGk3VW9IVlkKdtHzNqvk3+eO6PZta/4z3kxSB4w9QxYM
            iBA7qmoFldlmgEnlcVeKj8nNPqkAdbTR32Ii0/3ZDak8OKkoPPZM9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12xnm47mqs6rsw6e6fscva7s4pnaxmy2c7cvzfvx6knq497vx4s7qsp2u8g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T04:20:36Z"
    mac: ENC[AES256_GCM,data:gNv6DJgSdGYIZP6KDdbevKnsVIfCu+sEl6nhDYyqIZJuK7xd9HShxQp0wmQex4bkhyWs/VPkLng/WY68/pTotGzW8zSKDPVQe3KluTGKh9gxS6KUy0qm1QhdkhXAPvz2chZeVl83HfiwxqIHpZQ3BrUGbM1FOJhTpmjy2277mNs=,iv:gp+8G3zdjk3Hy2EWrBPmY+jLopeGIhiHxaxGnkooPFM=,tag:xEgOIejGRpPz/XsDKUV+TQ==,type:str]
    version: 3.13.0
