---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gcs-s3-credentials.sops.yaml
  - backup-target.yaml
  - gcs-backup-target.yaml
  - recurring-job.yaml
  - nodes.yaml
  - storage-classes.yaml
