---
- name: Create user accounts and configure access
  hosts: dev:baremetal
  become: true
  roles:
    - role: create-user
      vars:
        users:
          - name: pani
            groups: [sudo, promoter, talent, docker]
            shell: /usr/bin/zsh
            ssh_key: "~/.ssh/ansible.pub"
            password: "{{ pani_user_pass }}"
            sudoers:
              commands: ALL
              nopassword: true

