set unstable

pwd := absolute_path(".")

# Display this help
default:
  @just --list --unsorted

# Configure zsh
setup:
    {{pwd}}/setup.zsh setup

# Install oh-my-zsh and plugins
install:
    {{pwd}}/setup.zsh install
