---
- name: Create pani user
  ansible.builtin.user:
    name: pani
    state: present
    groups:
      - promoter
      - talent
      - sudo
    shell: /bin/zsh
    home: /home/pani

- name: Look up pani user info
  ansible.builtin.getent:
    database: passwd
    key: pani

- name: Set pani_home fact
  ansible.builtin.set_fact:
    pani_home: "{{ getent_passwd['pani'][4] }}"

- name: Set up SSH authorized key for pani
  ansible.posix.authorized_key:
    user: pani
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
    state: present

- name: Check if dotfiles repo exists
  ansible.builtin.stat:
    path: "{{ pani_home }}/dotfiles"
  register: dotfiles_dir

- name: Allow pani to access SSH agent socket
  ansible.builtin.file:
    path: "{{ ansible_env.SSH_AUTH_SOCK | dirname }}"
    mode: "0755"
    state: directory
  when: not dotfiles_dir.stat.exists

- name: Set agent socket permissions
  ansible.builtin.file:
    path: "{{ ansible_env.SSH_AUTH_SOCK }}"
    mode: "0666"
  when: not dotfiles_dir.stat.exists

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:Ivanipani/dotfiles.git
    dest: "{{ pani_home }}/dotfiles"
    version: main
    accept_newhostkey: true
  become: true
  become_user: pani
  environment:
    SSH_AUTH_SOCK: "{{ ansible_env.SSH_AUTH_SOCK }}"
  when: not dotfiles_dir.stat.exists

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ pani_home }}/.config"
    state: directory
    owner: pani
    group: pani
    mode: "0755"

- name: Run zsh setup script
  ansible.builtin.command:
    cmd: zsh ./setup.sh
    chdir: "{{ pani_home }}/dotfiles/zsh"
  become: true
  become_user: pani
  environment:
    HOME: "{{ pani_home }}"

- name: Configure neovim dotfiles
  ansible.builtin.command:
    cmd: zsh ./setup.sh
    chdir: "{{ pani_home }}/dotfiles/nvim"
  become: true
  become_user: pani
  environment:
    HOME: "{{ pani_home }}"

- name: Run zellij setup script
  ansible.builtin.command:
    cmd: zsh ./setup.sh
    chdir: "{{ pani_home }}/dotfiles/zellij"
  become: true
  become_user: pani
  environment:
    HOME: "{{ pani_home }}"

- name: Run version control setup script
  ansible.builtin.command:
    cmd: zsh ./setup.sh
    chdir: "{{ pani_home }}/dotfiles/vcs"
  become: true
  become_user: pani
  environment:
    HOME: "{{ pani_home }}"

- name: Install zplug
  ansible.builtin.git:
    repo: https://github.com/zplug/zplug.git
    dest: "{{ pani_home }}/.zplug"
    version: main
  become: true
  become_user: pani
