---
- name: Create promoter group
  ansible.builtin.group:
    name: promoter
    state: present
  when: ansible_os_family != "Darwin"

- name: Create talent group
  ansible.builtin.group:
    name: talent
    state: present
  when: ansible_os_family != "Darwin"

- name: Set up Ivan dev environment (macOS)
  ansible.builtin.include_tasks: ivan-dev-macos.yml
  when: ansible_os_family == "Darwin"

- name: Install Ivan's development tools (Linux)
  ansible.builtin.include_tasks: dev-tools-linux.yml
  when: ansible_os_family != "Darwin"

- name: Set up Ivan dev environment (Linux)
  ansible.builtin.include_tasks: ivan-dev-linux.yml
  when: ansible_os_family != "Darwin"
