- name: Install required packages
  ansible.builtin.package:
    name:
      - tmux
      - vim
      - git
      - curl
      - rsync
      - direnv
      - pass
    state: present
  become: true
  become_user: root

