[global]
keyboard = "en-us"
country = "us"
fqdn = "pve-home-02.local"
mailto = "root@localhost"
timezone = "America/New_York"
root-password = "changeme"
root-ssh-keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICTl/C06oyAMQiGgvUyH4eT2C0sPsIEqnT2nDNHDQ5j9 ivanperdomo@Ivans-MacBook-Pro.local"
]
reboot-on-error = false

[network]
source = "from-dhcp"

[network.interface-name-pinning]
enabled = true

[network.interface-name-pinning.mapping]
"3C:7C:3F:1F:96:AF" = "lan0"

[first-boot]
source = "from-iso"
ordering = "before-network"

[disk-setup]
filesystem = "ext4"
disk-list = ["nvme0n1"]
lvm = { hdsize = 100 }
