apiVersion: v1
data:
    id_ed25519: ENC[AES256_GCM,data:QyIDWWqARdaMsU3nhXczjYIBkU6CcpC4axVntP1FnQ1HlPCq7TSqYXBsxypcXrtsmwKT9Mi/uKWGDTr5M7FoP+nhudJoYRsRUtgq3fsN2rxn0wznB/KD5LHZNJhLoqwo6ePKYYbqEvJhnMN/0SYE5BPEgR2caqZC/NS/Hc/2MINEhZY9wcIAoVOa91Nhk64VjUJQj6Fs2R1NDk2DmVad41AHU9JH2vUWgYRkwJ05WWarIpWOQ+bf+4vEbBpui/LirLj5vDHAXL17w2F0X/8pEbypDocgab6tyrkKxVSmCDbK7b7CR4Ea1CRR3DHGieMkRvCyAVXkDnjEMXyWt01d5MZU2HVtwLdVTJ3N9hHqB1WGs+MAcfZrBty/0Rf0MVvqrRLdSI2kJeGQTv1qbbpFQVpwvAa9deNomFypTTRbWqIUic/cTr7pV28A3MOfKW2LmmJQJ6+9BibkmHR8yanBc20iJQjrHQhPtuy9MP/yxwaT+RcuA0GP0xlgvSuQg8194saXJx+4SlWs6zj26dTENDgnVzP673AlBnyKafU5fwHL9ie/4pUEEgetUuIqGUF0TXeXzrP5Qm1pKo+hlPGRA+8+qVo3W6DZlHWouBuoUCoD0WQ28VoDC+LMHdGYP80/q1VTV3F1sA2JaplJhYT7iFkHPU0MsgG6Nk1H0J/Pg/hzbV86TPZueJ81NeeYWtmMKzOmo9XjD0niVO+/m+s8bOdTbB9QBOg00sCz1kDEi/Zef/B72uwn3+i4ljeMCYuL,iv:qnMIojBZWX+zVYrFc266XE22Rbm/nlxsXxIHO2uvb3k=,tag:8pVF9et2PPiI3far4JfjKg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: doghouse-git
    namespace: tekton-ci
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaStPM3IvMTBma0Vqc1Bm
            RUZPTEtrK0IwWmtHYW93ZDJleDFvMitGMFJ3ClRnM1NKTHVTMHpaQ2krR2J3WTg2
            WWRFNW4wNFpyLzZZdlFHSHVob1grcE0KLS0tIDkraC9ZVENzS2NZb2hHUWE1RE9H
            SnZPMkYrOFlPT2ZwaTNLOE9FWHpuRmcKfXd2TZVOh6Ttpe9vYPAOo27ZOcRJCMnh
            e4vrIGNRp8/TVkwaCJ+sD2qjpyQkP6pXtdRq8zmBGV579wyktZRdNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12xnm47mqs6rsw6e6fscva7s4pnaxmy2c7cvzfvx6knq497vx4s7qsp2u8g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T01:35:31Z"
    mac: ENC[AES256_GCM,data:YM1xtWaCL13pldg5KVjBB69bwtMAQeHcaavZ5KlJQMWVGmgy1HO4BH+X4HTGVgjQ4rWgl+khU8NZ20KGW9uSlgeBKQqABjoc7NWnL3cXh6HDhi/W51FpQee8MUCw0T7Y0y/OjECpnJFDh944pskXtLlC+sjLqKazUlIlnbd9OPY=,iv:/tn0aszqtED6XfmxcY+H+J7S9Ul+cnBj5kfVP+Qv7BM=,tag:1gbnNVd1kmdcJ8IRVCU8IA==,type:str]
    version: 3.13.0
