---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - buildkit.yaml
  - pants-cache.yaml
  - common-tasks/clone-and-version.yaml
  - common-tasks/build-image.yaml
  - common-tasks/just-recipe.yaml
  - gar-pull.sops.yaml
  - doghouse-git.sops.yaml
  - gar-python.sops.yaml
