#!/bin/sh
# poochella-probe — inspect a bare machine's hardware and emit a paste-ready
# inventory fragment for ansible/inventory.yaml.
#
# Runs on the Debian 13 live-standard "probe" USB (built by img/live/build.sh).
# READ-ONLY: it never writes to, partitions, or wipes any target disk — it only
# reads sysfs + lsblk + a non-destructive `wipefs -n` signature scan.
#
# The per-disk attribute collection mirrors
# ansible/roles/host-disks/tasks/discover.yml so the emitted `storage.disks`
# selectors are byte-compatible with the host-disks role. Two deliberate
# differences, because here there is no installed OS yet:
#   1. No boot-disk auto-detect (`findmnt /` is the live overlay, not a target).
#      Instead we EXCLUDE the live USB medium and list every other fixed disk
#      as a candidate for the operator to classify.
#   2. Each disk is emitted as a data-disk selector by default, with an inline
#      note showing how to promote one to `select: boot` + `hw:` (the marker
#      roles/bootserv keys on to render the netboot preseed).

set -eu

# Trim leading/trailing + squeeze internal whitespace — must match how the
# host-disks role / bootserv resolver normalise lsblk model+serial strings.
norm() { awk '{ $1 = $1; print }'; }

# --- identify the live USB medium so we never offer it as a target disk -----
medium_src=""
for m in /run/live/medium /lib/live/mount/medium; do
    if [ -d "$m" ]; then
        medium_src=$(findmnt -no SOURCE "$m" 2>/dev/null || true)
        [ -n "$medium_src" ] && break
    fi
done
medium_disk=""
if [ -n "$medium_src" ]; then
    medium_disk=$(lsblk -dno PKNAME "$medium_src" 2>/dev/null || true)
    [ -z "$medium_disk" ] && medium_disk=$(basename "$medium_src")
fi

# --- DMI host hint (sysfs, no dmidecode needed) -----------------------------
dmi() { [ -r "/sys/class/dmi/id/$1" ] && norm < "/sys/class/dmi/id/$1" || true; }
sys_vendor=$(dmi sys_vendor)
product_name=$(dmi product_name)
product_serial=$(dmi product_serial)

date_str=$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || true)

echo "# ============================================================="
echo "# poochella inventory fragment — generated by poochella-probe"
[ -n "$date_str" ] && echo "# generated: $date_str"
echo "# host: ${sys_vendor:-?} ${product_name:-?}  (chassis serial: ${product_serial:-?})"
echo "# live USB medium: ${medium_disk:-unknown} (excluded from disk candidates)"
echo "# -------------------------------------------------------------"
echo "# Fill every <REPLACE...> and pick ONE disk as the boot/install disk"
echo "# before pasting under the right group in ansible/inventory.yaml."
echo "# ============================================================="
echo
echo "<REPLACE-hostname>:"
echo "  ansible_host: <REPLACE-hostname>.lan"
echo "  ip_address: 10.1.1.<REPLACE>        # assign a free static IP"
echo "  mac_addresses:"

# --- NICs -> mac_addresses --------------------------------------------------
nic_found=0
for n in /sys/class/net/*; do
    [ -e "$n" ] || continue
    name=${n##*/}
    [ "$name" = "lo" ] && continue
    [ -e "$n/device" ] || continue       # physical only (skip bridges/veth/etc)
    [ -d "$n/wireless" ] && continue     # skip wifi
    mac=$(cat "$n/address" 2>/dev/null || true)
    [ -n "$mac" ] || continue
    driver="?"
    [ -e "$n/device/driver" ] && driver=$(basename "$(readlink "$n/device/driver")")
    operstate=$(cat "$n/operstate" 2>/dev/null || echo "?")
    if [ "$operstate" = "up" ]; then
        spd=$(cat "$n/speed" 2>/dev/null || true)
        [ -n "$spd" ] && link="${spd}Mb/s" || link="up"
    else
        link="link-down"
    fi
    printf '    - "%s"   # %s  driver=%s  %s\n' "$mac" "$name" "$driver" "$link"
    nic_found=1
done
[ "$nic_found" = "0" ] && echo "    []   # NO physical NICs detected (?)"

echo "  storage:"
echo "    disks:"

# --- build the candidate disk list (no subshell, so empty-case works) -------
disks=""
for dev in $(lsblk -dpno NAME,TYPE | awk '$2=="disk"{print $1}'); do
    base=${dev#/dev/}
    [ "$base" = "$medium_disk" ] && continue          # never the live USB
    rm=$(lsblk -dno RM "$dev" | tr -d ' ')
    [ "$rm" = "1" ] && continue                       # removable: skip
    disks="$disks $dev"
done

if [ -z "$disks" ]; then
    echo "      []   # NO fixed (non-removable) disks detected besides the live USB"
fi

for dev in $disks; do
    rota=$(lsblk -dno ROTA "$dev" | tr -d ' ')
    szb=$(lsblk -bdno SIZE "$dev" | tr -d ' ')
    gib=$(( szb / 1073741824 ))
    model=$(lsblk -dno MODEL "$dev" | sed -e 's/[[:space:]]\{1,\}$//')
    serial=$(lsblk -dno SERIAL "$dev" | tr -d ' ')
    sigs=$(wipefs -n "$dev" 2>/dev/null | tail -n +2 | awk '{print $NF}' | paste -sd, -)
    pls=$(lsblk -no PARTLABEL "$dev" 2>/dev/null | sed '/^$/d' | paste -sd, -)
    floor=$(( (gib / 100) * 100 ))
    rotflag=false; [ "$rota" = "1" ] && rotflag=true

    echo "      # ---- $dev  ${gib}GiB  rotational=$rotflag  model='${model:-?}'  serial='${serial:-?}'"
    [ -n "$sigs" ] && echo "      #      existing signatures: $sigs"
    [ -n "$pls" ]  && echo "      #      existing partlabels: $pls"
    wipe=""; [ -n "$sigs" ] && wipe="
        wipe: force            # disk holds foreign signatures"
    echo "      - select: { model: \"${model}\", serial: \"${serial}\" }   # or { min_size_gib: $floor, rotational: $rotflag }$wipe"
    echo "        # promote to the boot/install disk instead with:"
    echo "        #   select: boot"
    echo "        #   hw: { model: \"${model}\", serial: \"${serial}\" }"
    echo "        partitions:"
    echo "          - label: <REPLACE-unique-partlabel>"
    echo "            size: \"0\"        # fill the disk"
    echo "            # worker (Longhorn) -> direct ext4, NO vg/thinpool:"
    echo "            mount: { path: /var/lib/longhorn-disks/<REPLACE-unique-partlabel>, fstype: ext4 }"
    echo "            # hypervisor instead -> PVE thin pool (delete the mount: line):"
    echo "            #   vg: vmdata"
    echo "            #   thinpool: vmthin"
    echo "            #   pve_storage: vms"
    echo "            #   content: images,rootdir,iso,vztmpl,snippets"
done
