apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:jAXNfgIF6OW2vo9whHthL7ApMxKLucgucmqu5gSvp03C8KkSwtmaZbSvHAQ6Z5zyzXOO52lNlu8ojJuxH+MPg30WIXoP8Hl4nA/JXbeU0JBZZNIUeXSR5MqxdbUxFvftaICQf056qOd1522s6WrbJ4XuZQLrtOdcccKQiKfKeSNhpV3EHDsyfeJuUIqw0f0cur2A97QKl5M4lg4BBsHMgHcdGxSGUCpP9/wHfpvF+W1UkH1jH2XJVg==,iv:tnyYbCXdMQnOrDmsN++maKAS35a89S97UHCN7HWAiMI=,tag:OTOXzKHNYlARGH9X5ECAWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWk0wM25EM0JUMTF5N2N6
            VVJyT1RXZGwzSWZLUVpjbUxONzhWeUFVMndjCjhNeGNoWndMZWlVRmtaV0t4cVcw
            T0ZMUnFiNU5YQ0d5WjJCRmZpTEUzeTAKLS0tIGJYNE9ZeDN0L3BxOXJMNDNjckpU
            TktxU0RlSjF4d1FxZWE1c2hXN29iRWcK6KnvNtlU/OYki0L1t1tegKCTb3jpXHx4
            /2F6Jsbjx+kd7tbrQjcdL1WREs+E44M8P1QGYvqV6sFvNDRAbwA/+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12xnm47mqs6rsw6e6fscva7s4pnaxmy2c7cvzfvx6knq497vx4s7qsp2u8g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T03:58:09Z"
    mac: ENC[AES256_GCM,data:7X2EihG5VnfKcKDThSeZJhyGsNujl89zldDo5caKZ3eRMPYxX9s1SHdwwvJud0UBSrQdhRZFeEWTJ1Q0u5pcNf0Hf1i17zyQFneOVGZI3XMs//VP0sIdEF0NalvyPJu+DuSXEoyi1CBQeAyNCcHucTlpPvMD1ARGP82VGL7b8w8=,iv:5SCHo1zlkRB95ijCyRMPUcAHaNWMUcR9pNgSYKyzyLc=,tag:ES+iCTPfYOGnviBnjJe3dQ==,type:str]
    version: 3.13.0
