---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Enable ufw and set default policy to deny incoming traffic
  community.general.ufw:
    state: enabled
    default: deny
    direction: incoming

- name: Set default policy to allow outgoing traffic
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow SSH traffic
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    comment: 'Allow SSH'

- name: Allow DNS traffic (TCP)
  community.general.ufw:
    rule: allow
    port: 53
    proto: tcp
    comment: 'Allow DNS TCP'

- name: Allow DNS traffic (UDP)
  community.general.ufw:
    rule: allow
    port: 53
    proto: udp
    comment: 'Allow DNS UDP'

- name: Allow DHCP traffic (UDP)
  community.general.ufw:
    rule: allow
    port: 67
    proto: udp
    comment: 'Allow DHCP'

- name: Allow HTTP traffic for pihole web admin
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    comment: 'Allow HTTP for pihole admin'
